fix compiler error on named type vs union, when the named type has a named alias
example
```odin
Scope :: any_dec

any_dec :: union {
  ^type_incomplete_declaration,
  ^type_enum_declaration,
  ...

sym_scope :: struct {
  syms : map[StrHandle][dynamic]symbol,
  parent_scope : Scope,
}

sym_scope_make :: proc(parent : Scope, alloc : mem.Allocator) -> sym_scope {
  return sym_scope{make(map[StrHandle][dynamic]symbol, 0, alloc), parent}           ---sometimes error here
}
```
depending on where the alias was declared, can output
```
Error: Cannot assign value 'parent' of type 'any_dec' to 'union {^type_incomplete_declaration, ...}' in a structure literal
        ... sym_scope{make(map[StrHandle][dynamic]symbol, 0, alloc), parent}
```